Update resolve conflict
OZEO-DOOZ/nrf_mesh_plugin pull request #259
Opened 2023-01-02 04:39 UTC by Hung6129

2023-01-02 21:43 UTC, R0m4in-dooz requested changes
Hello @Hung6129 ,
Thanks for the PR 👍
A few changes before we merge..

2023-01-02 21:43 UTC, ghost commented on example/lib/src/views/control_module/node.dart
>            Text(widget.node.uuid),
Don't hide unicast adr
```
Text('${nodeName ?? 'Node'} $nodeAddress' ),
```

2023-01-02 21:43 UTC, R0m4in-dooz commented on example/lib/src/views/home/home.dart
> +    //
Remove empty lines

2023-01-02 21:43 UTC, R0m4in-dooz commented on example/lib/src/views/home/home.dart
> +                  }
```suggestion
                  debugPrint("Downloading");
                  try {
                    Uint8List data = Uint8List.fromList(meshNetworkJson!.codeUnits);
                  MimeType type = MimeType.OTHER;
                  String path = await FileSaver.instance.saveAs("nRF_MeshNetwork", data, "json", type);
                    debugPrint("Download Completed.");
                  debugPrint(path);
                  } catch (e) {
                    debugPrint("Download Failed.\n\n$e");
                  }
```

2023-01-02 21:43 UTC, R0m4in-dooz commented on example/lib/src/views/scan_and_provisionning/scan_and_provisioning.dart
> +        debugPrint('start provisioning on android with device id: $deviceUUID');
Remove log

2023-01-02 21:43 UTC, R0m4in-dooz commented on example/lib/src/views/scan_and_provisionning/scan_and_provisioning.dart
> +        debugPrint('start provisioning on iOS with device id: $deviceUUID');
Remove log

2023-01-02 21:43 UTC, R0m4in-dooz commented on lib/src/utils/provisioning.dart
> +    provisionedMeshNode.nodeName = deviceToProvision.name;
I feel like it should not be done here or not like this. Can we try to do it earlier? For example, when the UnprovisionedMeshNode object is created ? Or maybe expose the parameter name in provisioning method..🤔

2023-01-02 21:43 UTC, R0m4in-dooz commented on example/lib/src/views/control_module/model.dart
> +            Text("ModelName:${getSigMeshName("0x${model.modelId.toRadixString(16).padLeft(4, '0').toUpperCase()}")}"),
Extract the hex value and use it here and in the other Text widget

2023-01-04 01:29 UTC, Hung6129 commented
Oh, about the node name
I think do it earlier it good too
It just i do not know a efficient way to do this 😢
If in the provisioning method where should i call it tho and same with UnprovisionedMeshNode object?
hope you can show me where is the best way to call and expose it
thanks

2023-01-11 19:59 UTC, R0m4in-dooz commented
Hi @Hung6129 ,

Changing the name ealier probably implies to edit some native code and I couldn't find it easily on GitHub to guide you. Maybe we can split your changes : revert the changes on the plugin and only keep changes in example app. If you follow the comments I added then we can merge the example app update and work on choosing name upon provisioning in a separate PR ?

2023-01-12 01:37 UTC, Hung6129 commented
Yeah sure !!
Can you tell me when we can start?
And what can i do to make it easier for you?

Btw it was mine first time to create a PR on a repo, hope u can skip out on the mistake 😟 

Thanks you

2023-01-12 20:58 UTC, R0m4in-dooz commented
You didn't make any mistakes. Thanks for your contribution 😃 

Make a commit on your branch that applies my suggestions and that removes the name change at the end of provisioning. So we can merge the example app update.
Then open a new issue for the feature request about having the newly provisioned node named after the given DiscoveredDevice.

2023-01-13 08:19 UTC, R0m4in-dooz commented
Thx for the removal and for other updates in the issues 👍
There are still some needed changes before we can merge 🚀

2023-02-16 15:01 UTC, R0m4in-dooz requested changes
Hello @Hung6129 

Would you have some time to apply my suggested changes ?
So we can merge your PR ;)

2023-02-16 15:01 UTC, ghost commented on example/lib/src/views/home/home.dart
> +
Remove empty lines

2023-02-16 15:21 UTC, Hung6129 reviewed
Resolve the changes

2023-02-16 15:21 UTC, Hung6129 commented on lib/src/utils/provisioning.dart
> +    provisionedMeshNode.nodeName = deviceToProvision.name;
Oh 
I think do it earlier it good too
It just i do not know a efficient way to do this 😢 
If in the provisioning method where should i call it tho and same with UnprovisionedMeshNode object? 
hope you can show me where is the best way to call and expose it
thanks

2023-02-16 15:21 UTC, Hung6129 commented on example/lib/src/views/control_module/node.dart
>            Text(widget.node.uuid),
My bad 😄

2023-02-16 15:21 UTC, Hung6129 commented on example/lib/src/views/home/home.dart
> +
ok sure

2023-02-16 15:21 UTC, Hung6129 commented on example/lib/src/views/home/home.dart
> +
ok i'm done now i create another PR ?

2023-02-16 21:15 UTC, ghost requested changes
Thanks 😊 LGTM except the pubspec.lock files update as it implies higher dart sdk constraint

2023-02-16 21:15 UTC, R0m4in-dooz commented on pubspec.lock
> +  dart: ">=2.19.0 <4.0.0"
I'd rather not merge such change as of now. Dart 2.17 is fine, isn't it ?

2023-02-16 21:15 UTC, R0m4in-dooz commented on example/pubspec.lock
> +  dart: ">=2.19.0 <4.0.0"
See comment on other pubspec.lock

2024-05-03 10:08 UTC, closed without merging